// JsFromRoutes CacheKey dd18fd11953d77d8d57caa6449b99c1e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  restore: definePathHelper('put', '/contacts/:id/restore'),
  list: definePathHelper('get', '/contacts'),
  create: definePathHelper('post', '/contacts'),
  new: definePathHelper('get', '/contacts/new'),
  edit: definePathHelper('get', '/contacts/:id/edit'),
  update: definePathHelper('patch', '/contacts/:id'),
  destroy: definePathHelper('delete', '/contacts/:id'),
}
