// JsFromRoutes CacheKey bea580ef29d127961c87d682ee5dcb5f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  exampleException: definePathHelper('get', '/error-500'),
  list: definePathHelper('get', '/'),
}
