// JsFromRoutes CacheKey f8ee4482980d57e901b2b701b80f7a6a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  exampleException: definePathHelper('get', '/error-500'),
  list: definePathHelper('get', '/'),
}
