// JsFromRoutes CacheKey 57157471fc16381e76daef1f5ca4fff4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  list: definePathHelper('get', '/'),
}
