// JsFromRoutes CacheKey a68891b2c79e5585a66fec24ce58b360
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import usersSessions from '~/api/Users/SessionsApi'
import reports from '~/api/ReportsApi'
import users from '~/api/UsersApi'
import organizations from '~/api/OrganizationsApi'
import contacts from '~/api/ContactsApi'
import dashboard from '~/api/DashboardApi'

export default {
  usersSessions,
  reports,
  users,
  organizations,
  contacts,
  dashboard,
}
