// JsFromRoutes CacheKey 860e5dc7e162ad1fbe8bf83c012c59e0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  list: definePathHelper('get', '/reports'),
}
