// JsFromRoutes CacheKey 4ecbb836a778f29574d3ebc8a6fdfce8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  list: definePathHelper('get', '/reports'),
}
