// JsFromRoutes CacheKey ae25c6737092d7b9028721c1ad375c8b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { request } from '@/services/ApiService'
import { pathFor } from '@/utils/PathHelper'

export default {
  pathFor,

  new: options =>
    request('get', '/login', options),

  create: options =>
    request('post', '/login', options),

  destroy: options =>
    request('delete', '/logout', options),
}
