// JsFromRoutes CacheKey 1f9213ad2b3718e6adac5e0a4ca2e5ad
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { request } from '@/services/ApiService'
import { pathFor } from '@/utils/PathHelper'

export default {
  pathFor,

  destroy: options =>
    request('delete', '/contacts/:id', options),

  update: options =>
    request('patch', '/contacts/:id', options),

  restore: options =>
    request('put', '/contacts/:id/restore', options),

  list: options =>
    request('get', '/contacts', options),

  create: options =>
    request('post', '/contacts', options),

  new: options =>
    request('get', '/contacts/new', options),

  edit: options =>
    request('get', '/contacts/:id/edit', options),
}
