// JsFromRoutes CacheKey 45f938265bc3955f933a9ee50f9cdf11
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { request } from '@/services/ApiService'
import { pathFor } from '@/utils/PathHelper'

export default {
  pathFor,

  exampleException: options =>
    request('get', '/error-500', options),

  list: options =>
    request('get', '/', options),
}
