// JsFromRoutes CacheKey a11c3bdb0c463fa4aa987c0c2dca5d0d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { request } from '@/services/ApiService'
import { pathFor } from '@/utils/PathHelper'

export default {
  pathFor,

  list: options =>
    request('get', '/reports', options),
}
