// JsFromRoutes CacheKey 41703f8eb19c8096ec9ac2fa9d2047ff
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { request } from '@/services/ApiService'
import { pathFor } from '@/utils/PathHelper'

export default {
  pathFor,

  restore: options =>
    request('put', '/users/:id/restore', options),

  list: options =>
    request('get', '/users', options),

  create: options =>
    request('post', '/users', options),

  new: options =>
    request('get', '/users/new', options),

  edit: options =>
    request('get', '/users/:id/edit', options),

  update: options =>
    request('patch', '/users/:id', options),

  destroy: options =>
    request('delete', '/users/:id', options),
}
